python3 model_scaling.py --generate_plot flops_scaling_gpt2_llama2_128_4096 --hf_access_token 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 
python3 model_scaling.py --generate_plot calflops_testing --hf_access_token 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 

python3 model_scaling.py --generate_plot calflops_dev_2 --hf_access_token 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
