proxy_location: EveryNode

http_options:
  host: 0.0.0.0
  port: 8000

grpc_options:
  port: 9000
  grpc_servicer_functions: []

applications:
- name: app1
  route_prefix: /bert
  import_path: ray_bert_model:bert_endpoint
  runtime_env: {}
  deployments:
  - name: BertBaseInferenceRay
  - name: BertQAInferenceRay
  - name: BertEndpointRay

- name: app2
  route_prefix: /roberta
  import_path: ray_roberta_model:roberta_endpoint
  runtime_env: {}
  deployments:
  - name: RobertaBaseInferenceRay
  - name: RobertaEndpointRay
